### ISSUE TITLE
Loading PDB file with zeroed CRYST records fails

### ISSUE THREAD

**Issue by SiriCamee** [JoaoRodrigues/interfacea#4]
Reading PDB files with `CRYST` records where the unit cell vectors are set to 0.0 gives an error on loading:

```
(interfacea) DN525uhm:selected_conf siricameevankeulen$ python check_pi_stacking.py frame_7535_c2.pdb 
Traceback (most recent call last):
  File "/Users/siricameevankeulen/anaconda3/envs/interfacea/lib/python3.6/site-packages/interfacea/__init__.py", line 74, in read
    struct = app.PDBFile(fullpath)
  File "/Users/siricameevankeulen/anaconda3/envs/interfacea/lib/python3.6/site-packages/simtk/openmm/app/pdbfile.py", line 95, in __init__
    pdb = PdbStructure(inputfile, load_all_models=True, extraParticleIdentifier=extraParticleIdentifier)
  File "/Users/siricameevankeulen/anaconda3/envs/interfacea/lib/python3.6/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 152, in __init__
    self._load(input_stream)
  File "/Users/siricameevankeulen/anaconda3/envs/interfacea/lib/python3.6/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 189, in _load
    self._periodic_box_vectors = computePeriodicBoxVectors(a_length, b_length, c_length, alpha, beta, gamma)
  File "/Users/siricameevankeulen/anaconda3/envs/interfacea/lib/python3.6/site-packages/simtk/openmm/app/internal/unitcell.py", line 78, in computePeriodicBoxVectors
    c = c - b*round(c[1]/b[1])
ZeroDivisionError: float division by zero
```

**Comment by JoaoRodrigues** [comment]
Sort of fixed. New data structures do not rely on OpenMM to read files. No analysis functionality implemented yet though, soon to come.
